'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root=__dirname;
const html=fs.readFileSync(path.join(root,'mytradingbot-dashboard.html'),'utf8');
const js=fs.readFileSync(path.join(root,'dashboard.js'),'utf8');
const css=fs.readFileSync(path.join(root,'dashboard.css'),'utf8');
const main=fs.readFileSync(path.join(root,'main.py'),'utf8');
const moduleSource=fs.readFileSync(path.join(root,'journal_pattern_gates.py'),'utf8');

for(const id of ['journalPatternGateSection','journalPatternGatePanel','journalPatternGateBadge','journalPatternSuggestions','journalPatternRules','journalPatternAudit']) assert.match(html,new RegExp(`id="${id}"`),`${id} ontbreekt`);
assert.match(js,/function renderJournalPatternGates\(/);
assert.match(js,/data-pattern-activate/);
assert.match(js,/data-pattern-deactivate/);
assert.match(js,/\/api\/v1\/pattern-gates\/activate/);
assert.match(js,/\/api\/v1\/pattern-gates\/deactivate/);
assert.match(js,/confirm:'DEACTIVEER REGEL'/);
assert.match(js,/prompt\(.*deactiveer/s);
assert.match(js,/Door eigenaar bevestigde dagboekregel/);
assert.match(js,/owner-confirmed journal rule/i);
assert.match(css,/\.pattern-suggestion/);
assert.match(css,/\.pattern-rule\.active/);
assert.match(css,/\.pattern-audit-item/);
assert.match(main,/def api_pattern_gate_activate/);
assert.match(main,/def api_pattern_gate_deactivate/);
assert.match(main,/require_owner\(\)/);
assert.doesNotMatch(main,/pattern-gates\/(?:override|relax|auto)/);
assert.match(moduleSource,/orderable_true_to_false_only/);
assert.match(moduleSource,/rules_never_auto_activate/);
assert.match(moduleSource,/suggestions_expire_rules_do_not/);
assert.doesNotMatch(moduleSource,/orderable\s*=\s*True/);
assert.match(moduleSource,/gate\.get\("orderable"\) is True/);
assert.match(moduleSource,/suggestion_expired/);
assert.match(moduleSource,/rule_deactivated/);
console.log('test_phase5c_pure_ui_r25c.js: 25/25 owner-only suggestion, activation, deactivation and ratchet assertions green');
